//
//  Locations.h
//  Transient Events
//
//  Created by Bruce E Truax on 10/8/09.
//  Copyright 2009 Diffraction Limited Design LLC. All rights reserved.
//

#import <CoreData/CoreData.h>

/**
 @brief Data object for Locations
 
 This data object is automatically generated by the CoreData model object.
 
 The purpose of the object is to allow properties to be accessed via 
 setters and getters or dot notation rather than needing to use 
 setValue: ForKey: and getValueForKey: methods.
 
 */

@interface Locations :  NSManagedObject  
{
	
}

@property (nonatomic, retain) NSNumber * Longitude; //!< location longintude
@property (nonatomic, retain) NSNumber * Latitude; //!< location latitude
@property (nonatomic, retain) NSString * Name;	//!< Common text name for location
@property (nonatomic, retain) NSNumber * Altitude; //!< altitude of location
@property (nonatomic, retain) NSString * SectionName; //!< section name - This is simply the first letter of the location name


@end



