//
//  Transient.h
//  Transient Events
//
//  Created by Bruce E Truax on 10/16/09.
//  Copyright 2009 Diffraction Limited Design LLC. All rights reserved.
//

#import <CoreData/CoreData.h>

/**
 @brief Data object for bookmarked transient events

 This data object is automatically generated by the CoreData model object.
 
 The purpose of the object is to allow properties to be accessed via 
 setters and getters or dot notation rather than needing to use 
 setValue: ForKey: and getValueForKey: methods.
 
*/


@interface Transient :  NSManagedObject  
{
}

@property (nonatomic, retain) NSString * Attribution;
@property (nonatomic, retain) NSString * EventDate;
@property (nonatomic, retain) NSData * Image1;
@property (nonatomic, retain) NSString * EventID;
@property (nonatomic, retain) NSString * EventStream;
@property (nonatomic, retain) NSNumber * VisibleMagnitude;
@property (nonatomic, retain) NSData * Image4;
@property (nonatomic, retain) NSData * FinderImage;
@property (nonatomic, retain) NSData * CellImage;
@property (nonatomic, retain) NSNumber * RightAscension;
@property (nonatomic, retain) NSData * ReferenceImage;
@property (nonatomic, retain) NSString * AlertDate;
@property (nonatomic, retain) NSData * Image3;
@property (nonatomic, retain) NSData * Image2;
@property (nonatomic, retain) NSNumber * Declination;
@property (nonatomic, retain) NSString * EventType;
@property (nonatomic, retain) NSString * FinderURLString;

@end



